---
- name: setup caddy
  hosts: all
  become: true

  tasks:

    - name: create containers dir
      ansible.builtin.file:
        name: /containers/caddy
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: copy builddir
      ansible.builtin.copy:
        src: container/
        dest: /containers/caddy/
        directory_mode: u=xrw,g=xr,o=xr
        mode: u=rw,g=r,o=r


    - name: build caddy container
      containers.podman.podman_image:
        name: caddy
        force: true
        path: /containers/caddy

    - name: make sure /etc/containers/systemd/ exists
      ansible.builtin.file:
        path: /etc/containers/systemd/
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: copy quadlet files
      ansible.builtin.copy:
        src: "services/{{ item }}"
        dest: "/etc/containers/systemd/{{ item }}"
        mode: u=rw,g=r,o=r
        force: true
      loop:
        - caddy.container
        - caddy_config.volume
        - caddy_data.volume

    - name: open port 80
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled

    - name: open port 443
      ansible.posix.firewalld:
        port: 443/tcp
        permanent: true
        state: enabled

    # - name: open port 80 for wireguard
    #   ansible.posix.firewalld:
    #     port: 80/tcp
    #     permanent: true
    #     state: enabled
    #     interface: wg0

    - name: start services
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: caddy.service
        state: restarted
        enabled: true
