version: 3

volumes:
    db:

services:
    postgresql:
        image: postgres
        restart: always
        volumes:
            - db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_PASSWORD = "${DB_PASSWORD}"
    
    nextcloud:
        image: nextcloud:apache
        restart: always
        ports:
            - 127.0.0.1:8001
        volumes:
            - netxcloud:/var/www/html
        environment:
            - POSTGRES_HOST=postgresql
        depends_on:
            - postgresql

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 127.0.0.1:8002
        environment:
            - PGADMIN_DEFAULT_EMAIL="max@mxrt.de"
            - PGADMIN_DEFAULT_PASSWORD="${PGADMIN_PASSWORD}"
