---
- name: base system setup
  hosts: all
  become: true

  tasks:

    - name: copy sources.list
      ansible.builtin.template:
        src: etc/apt/sources.list.j2
        dest: /etc/apt/sources.list
        mode: 0644

    - name: install vim, firewalld, zstd
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - firewalld
        - zstd

    - name: set hostname
      ansible.builtin.hostname:
        name: mxrt.de
        use: debian

    
