---
- name: setup sftp on port 2222 for scanning
  hosts: all
  become: true

  tasks:

    - name: create containers dir
      ansible.builtin.file:
        name: /containers
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: copy builddir
      ansible.builtin.copy:
        src: containers/sftp/
        dest: /containers/sftp/
        directory_mode: u=xrw,g=xr,o=xr
        mode: u=rw,g=r,o=r

    - name: make entrypoint executable
      ansible.builtin.file:
        path: /containers/sftp/entrypoint
        mode: u=rwx,g=rx,o=rx

    - name: build sftp container
      containers.podman.podman_image:
        name: sftp
        force: true
        path: /containers/sftp

    - name: make sure /etc/containers/systemd/ exists
      ansible.builtin.file:
        path: /etc/containers/systemd/
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: copy quadlet files
      ansible.builtin.copy:
        src: "services/{{ item }}"
        dest: "/etc/containers/systemd/{{ item }}"
        mode: u=rw,g=r,o=r
      loop:
        - sftp.container
        - sftp_scanner.volume
        - sftp_keys.volume

    - name: open port 2222
      ansible.posix.firewalld:
        port: 2222/tcp
        permanent: true
        state: enabled

    - name: start services
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: sftp.service
        state: restarted
