#use version 3.5 to specify network names
version: '3.5'

volumes:
    - portainer_data

caddy:
    build: ./caddy
    restart: always
    ports: 
        -80:80
        -443:443
    networks:
        - edge
        - service


portainer:
    build: ./portainer
    restart: always
    enviroment:
        - VIRTUAL_HOST=docker.mxrt.de
    networks:
        -service
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data 

        # pgsql:
#     build: ./pgsql
#     networks:
#         - backend

# nextcloud:
#     build: ./nextcloud
#     networks:
#         -service
#         -backend
    

networks:
    edge:
        name: mxrtde_edge
    service:
        name: mxrtde_service
    backend:
        name: mxrtde_backend
        internal: true