#use version 3.5 to specify network names
version: '3.5'

volumes:
    portainer_data:
    nextcloud_html:

services:
    caddy:
        build: ./caddy
        restart: always
        ports: 
            - 80:80
            - 443:443
        networks:
            - edge
            - service


    portainer:
        build: ./portainer
        restart: always
        environment:
            - VIRTUAL_HOST=docker.mxrt.de
        networks:
            - service
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data 

    pgsql:
        build: ./pgsql
        restart: always
        environment:
            - POSTGRES_PASSWORD="${DB_PASSWORD}"
        networks:
            - backend

    nextcloud:
        build: ./nextcloud
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=nextcloud
            - POSTGRES_PASSWORD="${NEXTCLOUD_DB_PASSWORD}"
            - POSTGRES_HOST=pgsql
        volumes:
            - nextcloud_html:/var/www/html
        networks:
            - service
            - backend
    

networks:
    edge:
        name: mxrtde_edge
    service:
        name: mxrtde_service
    backend:
        name: mxrtde_backend
        internal: true