---
- name: update all packages
  hosts: all
  become: true

  tasks:
    - name: update apt cache
      apt:
        update_cache: true
        force_apt_get: true
    - name: upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: true

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible after update"
        connect_timeout: 5
        reboot_timeout: 90
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
